<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Prepare user seed
        $users = [
            [
                'name' => 'Ahmed Rahman',
                'email' => 'ahmed1@example.com',
                'phone' => '01710000001',
                'user_type'=> 'tenant_user',
                'tenant_id' => 1,
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Karim Hasan',
                'email' => 'karim2@example.com',
                'phone' => '01710000002',
                'tenant_id' => 6,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rafiul Islam',
                'email' => 'rafiul3@example.com',
                'phone' => '01710000003',
                'tenant_id' => 7,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sabbir Hossain',
                'email' => 'sabbir4@example.com',
                'phone' => '01710000004',
                'tenant_id' => 4,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Tanvir Ahmed',
                'email' => 'tanvir5@example.com',
                'phone' => '01710000005',
                'tenant_id' => 6,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Nusrat Jahan',
                'email' => 'nusrat6@example.com',
                'phone' => '01710000006',
                'tenant_id' => 7,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Mithila Akter',
                'email' => 'mithila7@example.com',
                'phone' => '01710000007',
                'tenant_id' => 5,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Fahim Chowdhury',
                'email' => 'fahim8@example.com',
                'phone' => '01710000008',
                'tenant_id' => 3,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Arif Hossain',
                'email' => 'arif9@example.com',
                'phone' => '01710000009',
                'tenant_id' => 2,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Jannat Ara',
                'email' => 'jannat10@example.com',
                'user_type'=> 'tenant_user',
                'tenant_id' => 9,
                'phone' => '01710000010',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Imran Khan',
                'email' => 'imran11@example.com',
                'phone' => '01710000011',
                'tenant_id' => 3,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Farzana Rahman',
                'email' => 'farzana12@example.com',
                'phone' => '01710000012',
                'tenant_id' => 2,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rakibul Hasan',
                'email' => 'rakib13@example.com',
                'phone' => '01710000013',
                'tenant_id' => 3,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sumaiya Islam',
                'email' => 'sumaiya14@example.com',
                'phone' => '01710000014',
                'tenant_id' => 4,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Shakib Al Hasan',
                'email' => 'shakib15@example.com',
                'phone' => '01710000015',
                'tenant_id' => 6,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Nadia Sultana',
                'email' => 'nadia16@example.com',
                'phone' => '01710000016',
                'tenant_id' => 1,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Mahmuda Hasan',
                'email' => 'mahmuda17@example.com',
                'phone' => '01710000017',
                'tenant_id' => 3,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sohel Rana',
                'email' => 'sohel18@example.com',
                'phone' => '01710000018',
                'tenant_id' => 2,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sadia Islam',
                'email' => 'sadia19@example.com',
                'phone' => '01710000019',
                'tenant_id' => 4,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rashed Islam',
                'email' => 'rashed20@example.com',
                'phone' => '01710000020',
                'tenant_id' => 7,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Tahmina Akter',
                'email' => 'tahmina21@example.com',
                'phone' => '01710000021',
                'tenant_id' => 7,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sifat Hossain',
                'email' => 'sifat22@example.com',
                'phone' => '01710000022',
                'tenant_id' => 6,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Jannatul Ferdous',
                'email' => 'jannatul23@example.com',
                'phone' => '01710000023',
                'tenant_id' => 6,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sohel Islam',
                'email' => 'sohel24@example.com',
                'phone' => '01710000024',
                'tenant_id' => 4,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rashedul Islam',
                'email' => 'rashedul25@example.com',
                'phone' => '01710000025',
                'tenant_id' => 5,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Tahmina Islam',
                'email' => 'tahmina26@example.com',
                'phone' => '01710000026',
                'tenant_id' => 1,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sifatul Islam',
                'email' => 'sifatul27@example.com',
                'phone' => '01710000027',
                'tenant_id' => 1,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Jannatul Ferdous',
                'email' => 'jannatul28@example.com',
                'user_type'=> 'tenant_user',
                'tenant_id' => 3,
                'phone' => '01710000028',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sohel Islam',
                'email' => 'sohel29@example.com',
                'phone' => '01710000029',
                'tenant_id' => 1,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rashedul Islam',
                'email' => 'rashedul30@example.com',
                'phone' => '01710000030',
                'tenant_id' => 2,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Tahmina Islam',
                'email' => 'tahmina31@example.com',
                'phone' => '01710000031',
                'tenant_id' => 4,
                'user_type'=> 'tenant_user',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sifatul Islam',
                'email' => 'sifatul32@example.com',
                'phone' => '01710000032',
                'tenant_id' => 5,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Jannatul Ferdous',
                'email' => 'jannatul33@example.com',
                'phone' => '01710000033',
                'tenant_id' => 4,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Sohel Islam',
                'email' => 'sohel34@example.com',
                'phone' => '01710000034',
                'tenant_id' => 8,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
            [
                'name' => 'Rashedul Islam',
                'email' => 'rashedul35@example.com',
                'phone' => '01710000035',
                'tenant_id' => 9,
                'user_type'=> 'tenant_customer',
                'password' => Hash::make('password123'),
            ],
        ];
        User::insert($users);
    }
}
